config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  get 'callback' => 'home#callback'
  get 'health' => 'shops#health'
  get 'update_table' => 'shops#update_table'
  mount ShopifyApp::Engine, at: '/'

  resources :shops, except: [:index] do
    member do
      get :login
      get :setting
    end
  end

  namespace :webhook do
    resources :products, only: [:create]
    resources :orders, only: [:create]
    resources :transactions, only: [:create]
    resources :customers, only: [:create]
    resources :fulfillments, only: [:create]
    resources :uninstall, only: [:create]
  end

end

app/controllers/shops_controller.rb
class ShopsController < ShopifyApp::AuthenticatedController
  include WebhookModule
  include ConnectionModule
  include DatabaseModule

  before_filter :prepare_notifier
  before_action :init_shop
  before_action :init_company_name, :only => [:show, :edit]

  # Handles ajax call to update the table in Dashboard
  def update_table
    init_table
  end

  # Renders the login view component
  def login
    
  end

  # Renders the setting view component
  # If the shop is already configured then redirect to show
  def setting
    if @shop
      if @shop.config_status == true
        redirect_to shop_path(@shop)
      end
    end
  end

  # Called when user submitted the first time setting
  # Redirects to show
  def create
    if @shop
      update_shop(params["shop_token"], true)
      if params["sync"]
        update_sync_status(@shop, true)
        ShopSyncJob.perform_later(@shop)
        flash[:notice] = "Syncing in Background.."
      else
        flash[:notice] = "Configuration Successfully Saved"
      end
      
      save_to_log(params)
      add_webhooks(@shop)
      redirect_to shop_path(@shop)
    else
      redirect_to :back
    end

  rescue Exception => e
    puts e.message
    puts e.backtrace.inspect
    if @shop
      update_shop(params["shop_token"], false)
    end
    
    flash[:notice] = "Something went wrong, please try again"
    redirect_to :back
  end

  # Renders the show view component
  def show
    if @company_name.nil?
      @company_name = ""
    end
    init_table
  end

  # Renders the edit view component
  def edit
    if @company_name.nil?
      @company_name = ""
    end

    @checked = false
    if @shop != nil
      if @shop.webhook_status
        @checked = true
      end
    end
    # Probably not being used
    # ||= means assign if not assigned
    session[:return_to] ||= request.referer 
  end

  # Called when webhook status update is submitted from edit page
  def update
    if @shop != nil
      if params["webhook_checkbox"] == "true"
        WebhookChangeJob.perform_later("add", @shop)
        flash[:notice] = "Webhook Updated"
      else
        WebhookChangeJob.perform_later("remove", @shop)
        flash[:notice] = "Webhook Updated"  
      end
    end
    
    render nothing: true
  end

  # Not being used
  # Can be used when the need to delete shop arises
  def destroy
    if @shop != nil
      SentDatum.delete_all(shop_domain: "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}")
      SyncLog.delete_all(shop_domain: "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}")
      remove_webhooks(@shop)
      @shop.delete
    end

    webhook = ShopifyAPI::Webhook.new(:topic => "app/uninstalled", :address => ENV["UNINSTALL_PATH"], :format => "json")
    webhook.save
    flash[:notice] = "All Data Cleaned Successfully"
    
    redirect_to root_path, :shop => "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}"
  end

  # Health check endpoint
  def health
    render nothing: true
  end

  private
    # Initialize the system log table in the show component
    def init_table
      @table_data = Array.new
      @last_datum = SentDatum.where(["(response = ? OR response = ?) AND shop_domain = ?", "201  Created", "200  OK", "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}"]).last
      if @last_datum != nil
        # Get every sending activity as table data except update
        # Only take the last 10 data
        @table_data = SentDatum.where(["created_at_shopify != ? AND shop_domain = ? AND kind NOT LIKE ?", "NULL", "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}", "update%"]).order(created_at: :desc).first(10)
        
        @fail_array = Array.new
        # Initialize message for every sending failure
        @table_data.each do |datum|
          if datum.response != "200  OK" && datum.response != "201  Created"
            temp_hash = {
              "kind" => "#{datum.kind}",
              "response" => "#{datum.response}"
            }
            @fail_array.push(temp_hash)
          end
        end
      end

      # If something is synced and the data in the table is less than 10
      # Count and append the syncing data to the table data
      if SyncLog.find_by(shop_domain: "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}") && @table_data.count < 10
        product = get_sync_log("Sync Products")
        customer = get_sync_log("Sync Customers")
        order = get_sync_log("Sync Orders")
        @step_count = 0
        @success_count = 0
        sync_hash = {
          "type" => "sync_data",
          "message" => "Synced: "
        }

        # If the products is successfully synced
        if product 
          # Check whether there is a sent product or not
          product_log_item = SentDatum.find_by(kind: "Create product (batch)", shop_domain: "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}")
          if product_log_item.nil?
            @product_message = "No Product To Sync"
          else
            @product_message = product_log_item.response
          end
          
          @sync_product_total = product.total
          @sync_product_success = product.success
          sync_hash["message"] += "Products #{@sync_product_success} out of #{@sync_product_total}"
          sync_hash["date"] = product.updated_at
          @step_count += 1

          # Only counts as success if every product is successfully synced
          if @sync_product_success == @sync_product_total
            @success_count += 1
          end
        end

        # If the customers is successfully synced
        if customer
          # Check whether there is a sent customer or not
          customer_log_item = SentDatum.find_by(kind: "Create customer (batch)", shop_domain: "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}")
          if customer_log_item.nil?
            @customer_message = "No Customer To Sync"
          else
            @customer_message = customer_log_item.response
          end
          @sync_customer_total = customer.total
          @sync_customer_success = customer.success
          sync_hash["message"] += ", Customers #{@sync_customer_success} out of #{@sync_customer_total}"
          sync_hash["date"] = customer.updated_at
          @step_count += 1

          # Only counts as success if every product is successfully synced
          if @sync_customer_success == @sync_customer_total
            @success_count += 1
          end
        end

        # If the orders is successfully synced
        if order
          # Check whether there is a sent order or not
          order_log_item = SentDatum.find_by(kind: "Create order (batch)", shop_domain: "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}")
          if order_log_item.nil?
            @order_message = "No Order To Sync"
          else
            @order_message = order_log_item.response
          end
          @sync_order_total = order.total
          @sync_order_success = order.success
          sync_hash["message"] += ", Orders #{@sync_order_success} out of #{@sync_order_total}"
          sync_hash["date"] = order.updated_at
          @step_count += 1

          # Only counts as success if every product is successfully synced
          if @sync_order_success == @sync_order_total
            @success_count += 1
          end
        end

        if @success_count == 3
          @icon = "glyphicon-ok-sign"
          @color = "green"
        elsif @success_count == 0
          @icon = "glyphicon-remove-sign"
          @color = "red"
        else
          @icon = "glyphicon-ok-sign"
          @color = "#FFCF00" # Dark yellow
        end

        # Append the sync information to table data
        if @table_data != nil
          @table_data << sync_hash
        end
      end

      if @shop != nil
        test = @table_data.last
        # Check whether the sync information still exists within the table data or not
        if @shop.sync_status && test != nil && test["type"] == "sync_data"
          # See @sync usage at the _log_table partial
          @sync = true
        end
      end
    end

    # Initialize the company name to show
    def init_company_name
      if Log.where(shop_domain: "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}").select("comp_name").last != nil
        @company_name = Log.where(shop_domain: "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}").select("comp_name").last.comp_name
      end
    end

    # Initialize @shop so it can be used
    def init_shop
      @shop = Shop.find_by(shopify_token: "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).token}")
    end

    # Append the shop name to the email sent everytime an error occurs
    def prepare_notifier
      shop = Shop.find_by(shopify_token: "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).token}")
      if shop
        request.env["exception_notifier.exception_data"] = {
          :current_shop => shop.shopify_domain  
        }
      end
    end

    def get_sync_log(kind)
      SyncLog.where(["kind = ? AND shop_domain = ?", "#{kind}", "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}"]).last
    end
end

app/views/shops/_footer.html.haml
.footer
  .container
    .text-muted
      %center
        Having trouble or want to give us feedback on this app? #{link_to("Let us know.", "https://www.jurnal.id/en/support", :target => "_blank")}

app/views/shops/_log_table.html.haml
= javascript_include_tag "modal"

%table{:class => "table table-hover table-striped table-scroll"}
  %thead
    %tr
      %th 
      %th Date
      %th Message
      %th Status
      %th Action
  %tbody
    -if @sync
      -if @step_count != 3
        %tr
          %th{:scope => "row"}
          %td
          %td
            %small Currently syncing your data..
          %td
          %td
            %i{:class => "fa fa-spinner fa-pulse fa-3x fa-fw margin-bottom"}

    -@table_data.each_with_index do |item, index| 
      -if item["type"] != nil
        -if @step_count == 3
          .div{:id => "sync_data"}
            %tr
              %th{:scope => "row"}
                .glyphicon{:class => "#{@icon}", :style => "color:#{@color}"} 
              %td
                %small= item["date"].strftime("%A, %d %B %Y, %H:%M:%S")
              %td
                %small= item["message"]
              %td
                -if @color == "red"
                  %small Sync failed
                -elsif @color == "green"
                  %small Sync is successful
                -else
                  %small Unable to sync some data
              %td
                =button_tag "View Details", :class => "btn btn-info btn-xs", "data-toggle" => "modal", "data-target" => "#sync_information"
      -else
        %tr
          %th{:scope => "row"}
            -if item.response == "200  OK" || item.response == "201  Created"
              .glyphicon.glyphicon-ok-sign{:style => "color:green"}
            -else
              .glyphicon.glyphicon-remove-sign{:style => "color:red"} 
          %td
            %small= item.created_at.strftime("%A, %d %B %Y, %H:%M:%S")
          %td
            %small= item.kind
          %td
            -if item.response == "201  Created"
              %small Created
            -elsif item.response == "200  OK"
              %small Updated
            -else
              %small Failed
          %td
            -if item.response != "200  OK" && item.response != "201  Created"
              =button_tag "View Details", :class => "btn btn-info btn-xs btn-detail", :id => "#{item.kind.gsub(/\s+/, "")}", "data-toggle" => "modal", "data-target" => "#fail_information"
              .hiddenfield
                -fail_info = @fail_array[@fail_array.find_index{|x| x["kind"] == "#{item.kind}"}]
                =hidden_field_tag "#{item.kind.gsub(/\s+/, "")}", fail_info["response"]


.modal.fade#sync_information
  .modal-dialog
    .modal-content
      .modal-header
        .pull-right
          %button#close_sync_modal{:class => "close"} x
        .h3 Sync Information
      .modal-body
        .row
          .col-xs-2
            %p Products:
          .col-xs-10
            %textarea{"readonly" => true, "style" => "width:100%; height:100px;"}
              =@product_message
        .row
          .col-xs-2
            %p Customers:
          .col-xs-10
            %textarea{"readonly" => true, "style" => "width:100%; height:100px;"}
              =@customer_message
        .row
          .col-xs-2
            %p Orders:
          .col-xs-10
            %textarea{"readonly" => true, "style" => "width:100%; height:100px;"}
              =@order_message

      .modal-footer
        .text-center
          = button_tag "Got it!", :class => "btn-success", :id => "confirm_sync"


.modal.fade#fail_information
  .modal-dialog
    .modal-content
      .modal-header
        .pull-right
          %button#close_fail_modal{:class => "close"} x
        .h3 Log Detail
      .modal-body
        .row
          .col-xs-3
            Error Information: 
          .col-xs-9
            .modal_info

      .modal-footer
        .text-center
          = button_tag "Got it!", :class => "btn-success", :id => "confirm_fail"

app/views/shops/edit.html.haml
= stylesheet_link_tag "style"
= stylesheet_link_tag "content"

- content_for :javascript do
  :javascript
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.loadingOff();
      ShopifyApp.Bar.initialize({
        title: "Configuration",
        icon: "#{asset_path('Logo_small.png')}"
      });
    });

    $("[name='webhook_checkbox']").bootstrapSwitch();
    $('input[name="webhook_checkbox"]').on('switchChange.bootstrapSwitch', function(){
      $.ajax({
        url: "#{shop_path}",
        type: 'PATCH',
        data: {"webhook_checkbox": this.checked}
      });
    });
    $(function() {
      $('[data-toggle="tooltip"]').tooltip()
    });

.content
  .container
    .row
      .col-xs-1
        %img{:src => "#{asset_path('Logo_small.png')}", :class => "img-thumbnail", "min-width" => "50", "min-height" => "50"}
      .col-xs-3
        .row
          %h4= @company_name
        .row
          %p By: Jurnal
    
    %br
    .row
      .col-xs-5
        %body Webhooks :
        = check_box_tag 'webhook_checkbox', 'reset', @checked, "data-size" => "mini"
        %i{:class => "fa fa-question-circle-o", "data-toggle" => "tooltip", "data-placement" => "right", :title => "When activated, it allows the system to automatically send data to Jurnal when it detected recently created and/or updated Order, Product, and Customer"}

    %br
    .row
      .col-xs-6
        .panel{:class => "panel-warning"}
          .panel-heading
            .h4
              %font{:color => "black"} Notice 
          .panel-body
            .row
              .col-xs-12
                %body To track product category and product quantity, Jurnal Pro or Enterprise account is required
    %br
    .row
      .col-xs-6
        .pull-left
          = link_to "Back", {:controller => "shops", :action => "show"}, :class => "btn btn-primary", :target => "_self", :method => "get", :onclick => "ShopifyApp.Bar.loadingOn()"

=render "footer"

app/views/shops/login.html.haml
= stylesheet_link_tag "style"
= stylesheet_link_tag "content"

- content_for :javascript do
  :javascript
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.loadingOff();
      ShopifyApp.Bar.initialize({
        title: "Login",
        icon: "#{asset_path('Logo_small.png')}"
      });
    });
.container
  .row{:style => "padding-top: 20px;"}
    .jumbotron.login-content
      .h4 Connect your Jurnal account to get started
      .center-item.login-picture
        %img{:src => "#{asset_path('connect-image-jurnal.png')}"}
      .center-item
        No changes will be made to your Jurnal account until setup is complete
  .row
    .login-content
      %a{:href => ENV["AUTH_PATH"], :class => "btn btn-info", :target => "_parent"} Connect with Jurnal
  .row
    .login-content.center-item
      =link_to("Don't have an account? Register now for 14-days free trial", "https://my.jurnal.id/en/users/sign_up", :target => "_blank")

=render "footer"

app/views/shops/setting.html.haml
= stylesheet_link_tag "style"
= stylesheet_link_tag "content"

- content_for :javascript do
  :javascript
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.loadingOff();
      ShopifyApp.Bar.initialize({
        title: "First Time Configuration",
        icon: "#{asset_path('Logo_small.png')}"
      });
    });
    $(function() {
      $('[data-toggle="tooltip"]').tooltip()
    })

    $("#feature-text").click(function(event) {
      $("#feature_modal").modal('show');
    });

    $("#close_feature_modal").click(function(event) {
      $("#feature_modal").modal('hide');
    });

    $("#confirm_feature").click(function(){
      $("#feature_modal").modal('hide');
    });

    window.onclick = function(event) {
      if (event.target == $("#feature_modal")) {
        $("#feature_modal").modal('hide');
      }
    }

.body
  .content
    .container
      .row
        .col-xs-6
          %form{:role => "form", :name => "configForm", :action => "#{shops_path}", :method => "POST", :onsubmit => "ShopifyApp.Bar.loadingOn()"}
            .row
              .col-xs-8
                .form-group
                  %label{:for => "name"}Company Name
                  %i{:class => "fa fa-question-circle-o", "data-toggle" => "tooltip", "data-placement" => "right", :title => "Your Jurnal's company name"}
                  %input{:class => "form-control", :type => "text", :name => "name", :placeholder => "Your Company Name"}
              
            .row
              .col-xs-12
                %small Sync All Data From Beginning:
                %input{:type => "checkbox", :name => "sync", :value => "true"}
                %i{:class => "fa fa-question-circle-o", "data-toggle" => "tooltip", "data-placement" => "right", :title => "Sync all your shop's data to Jurnal"}
            %br
            %br
            .row
              .col-xs-4
              .col-xs-3
                = button_tag "Complete Setup", data: {disable_with: "Processing.."}, class: "btn btn-success"

            = hidden_field_tag :authenticity_token, form_authenticity_token
            = hidden_field_tag :shop, "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).url}"
            = hidden_field_tag :shop_token, "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).token}"

    %br
    .container
      .row
        .col-xs-7
          .panel{:class => "panel-warning"}
            .panel-heading
              .h4
                %font{:color => "black"} Notice 
            .panel-body
              .row
                .col-xs-12
                  .h5 This application is for syncing your shopify data to your Jurnal company in real-time (i.e. every change made in your shopify store will be directly forwarded to your Jurnal company).
                  .small
                    %a#feature-text{"data-target"=>"#feature_modal"} 
                      Features list

.modal.fade#feature_modal
  .modal-dialog
    .modal-content
      .modal-header
        .pull-right
          %button#close_feature_modal{:class => "close"} x
        .h4 Features List
      .modal-body
        %table{:class => "table table-hover"}
          %tbody
            %tr
              %td 
              %td.feature-content Pro or Enterprise
              %td.feature-content Starter
            %tr
              %td Sync customers to customers
              %td.feature-content
                %i{:class => "fa fa-check"}
              %td.feature-content
                %i{:class => "fa fa-check"}
            %tr
              %td 
                Sync products to products
              %td.feature-content
                %i{:class => "fa fa-check"}
              %td.feature-content
                %i{:class => "fa fa-check"}
            %tr
              %td#sub-feature 
                Product Category
              %td.feature-content
                %i{:class => "fa fa-check"}
              %td.feature-content
                %i{:class => "fa fa-times"}
            %tr#sub-feature
              %td#sub-feature
                Product Tracking
              %td.feature-content
                %i{:class => "fa fa-check"}
              %td.feature-content
                %i{:class => "fa fa-times"}
            %tr
              %td Sync orders to sales invoices
              %td.feature-content
                %i{:class => "fa fa-check"}
              %td.feature-content
                %i{:class => "fa fa-check"}
              

      .modal-footer
        .text-center
          = button_tag "Got it!", :class => "btn-success", :id => "confirm_feature"
                  

=render "footer"

app/views/shops/show.html.haml
= stylesheet_link_tag "style"
= stylesheet_link_tag "content"
= javascript_include_tag "table_update"

- content_for :javascript do
  :javascript
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.loadingOff();
      ShopifyApp.Bar.initialize({
        title: "Dashboard",
        icon: "#{asset_path('Logo_small.png')}"
      });
    });

    $(".btn-detail").click(function() {
      $(".modal_info").text($(".hiddenfield").find("#" + this.id).val());
    });

    if (#{@shop.sync_status} == 1) {
      $(function() {
        updateTable();
      })
    }


.content
  .container
    .row
      .col-md-4
        .row
          .col-md-3
            %img{:src => "#{asset_path('Logo_small.png')}", :class => "img-thumbnail", "min-width" => "50", "min-height" => "50"}

          .col-md-4
            .row
              .h4= @company_name
              
            .row
              %body By: Jurnal
        
          .col-md-5
            .pull-right
              = button_to "Configure", {:controller => "shops", :action => "edit"}, :class => "btn btn-success", :target => "_self", :method => "get", :onclick => "ShopifyApp.Bar.loadingOn()"
      
      .col-md-7
        .panel{:class => "panel-success"}
          .panel-heading
            %font{:color => "black"} System Log

          .div{:id => "log_table"}
            =render "log_table"

=render "footer"

app/views/shops/update_table.js.erb
$("#log_table").html("<%= escape_javascript(render partial: "log_table") %>");