config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  get 'callback' => 'home#callback'
  get 'health' => 'shops#health'
  get 'update_table' => 'shops#update_table'
  mount ShopifyApp::Engine, at: '/'

  resources :shops, except: [:index] do
    member do
      get :login
      get :setting
    end
  end

  namespace :webhook do
    resources :products, only: [:create]
    resources :orders, only: [:create]
    resources :transactions, only: [:create]
    resources :customers, only: [:create]
    resources :fulfillments, only: [:create]
    resources :uninstall, only: [:create]
  end

end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  # Root url, check if the user already has an access token
  # If no access token, redirect the user to login page
  # Redirection is done in the view component
  def index
    @shop = Shop.find_by(shopify_token: "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).token}")
    unless @shop.access_token.nil?
      @authorized = true
    end
  end

  # Receive callback from Jurnal oauth and store the access token
  def callback
    @shop = Shop.find_by(shopify_token: "#{ShopifyApp::SessionRepository.retrieve(session[:shopify]).token}")
    if params["access_token"]
      @shop.access_token = params["access_token"]
      @shop.save
    end
    redirect_to root_path
  end
end

app/views/home/index.html.haml
= stylesheet_link_tag "style"
= stylesheet_link_tag "content"

- content_for :javascript do
  :javascript
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.loadingOff();
      ShopifyApp.Bar.initialize({
        title: "Loading",
        icon: "#{asset_path('Logo_small.png')}"
      });
    });

%head
  -if @authorized
    %meta{"http-equiv" => "refresh", :content => "3;URL=#{setting_shop_path(@shop)}"}
  -else
    %meta{"http-equiv" => "refresh", :content => "3;URL=#{login_shop_path(@shop)}"}

%h4 Please wait a moment...